apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-mysql-devops
  name: demo-mysql-devops
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: demo-mysql-devops
  template:
    metadata:
      labels:
        app: demo-mysql-devops
    spec:
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
          imagePullPolicy: Always
          name: ks-sample
          env:
            - name: MYSQL_HOST
              value: $MYSQL_HOST
            - name: MYSQL_PORT
              value: $MYSQL_PORT
            - name: MYSQL_USERNAME
              value: $MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              value: $MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
