apiVersion: v1
kind: Service
metadata:
  labels:
    component: demo-mysql-devops-env
  name: ks-sample-dev-env
  namespace: test
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30863
  selector:
    app: demo-mysql-devops-env
  sessionAffinity: None
  type: NodePort
